# https://taskfile.dev
version: '3'

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  check:
    desc: "Validate all plugins and marketplace"
    cmds:
      - claude plugin validate plugins/devops-infrastructure
      - claude plugin validate plugins/software-engineering
      - claude plugin validate plugins/go-specialist
      - claude plugin validate .

  check-versions:
    desc: "Check version synchronization between marketplace.json and plugin.json files"
    cmds:
      - ./scripts/check-versions.sh

  update-version:
    desc: "Update version for affected plugins (usage: task update-version -- patch|minor|major)"
    cmds:
      - ./scripts/update-version.sh {{.CLI_ARGS}}
